# Generated by Django 4.2.21 on 2025-05-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextBlock',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('belief', 'Belief'), ('value', 'Value'), ('preference', 'Preference'), ('position', 'Position')], max_length=20)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_blocks', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
