# Generated by Django 4.2.21 on 2025-05-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextPermission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('accessor_id', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('full', 'Full Access'), ('anonymized', 'Anonymized Access'), ('vector_only', 'Vector Only')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='memories.contextblock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
