# Generated by Django 4.2.21 on 2025-05-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('embedding_method', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_log', to='memories.contextblock')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
